Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/salud.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.salud.com:7050

  - &Hospital
    Name: HospitalMSP
    ID: HospitalMSP
    MSPDir: ../organizations/peerOrganizations/hospital.salud.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('HospitalMSP.admin', 'HospitalMSP.peer', 'HospitalMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('HospitalMSP.admin', 'HospitalMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('HospitalMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('HospitalMSP.peer')"
    AnchorPeers:
      - Host: peer0.hospital.salud.com
        Port: 7051

  - &MinSalud
    Name: MinSaludMSP
    ID: MinSaludMSP
    MSPDir: ../organizations/peerOrganizations/minsalud.salud.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('MinSaludMSP.admin', 'MinSaludMSP.peer', 'MinSaludMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('MinSaludMSP.admin', 'MinSaludMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('MinSaludMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('MinSaludMSP.peer')"
    AnchorPeers:
      - Host: peer0.minsalud.salud.com
        Port: 9051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.salud.com:7050
  EtcdRaft:
    Consenters:
      - Host: orderer.salud.com
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/salud.com/orderers/orderer.salud.com/tls/server.crt
        ServerTLSCert: ../organizations/ordererOrganizations/salud.com/orderers/orderer.salud.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  SaludGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Hospital
        - *MinSalud
      Capabilities: *ApplicationCapabilities
